edit Block.java/timestamp
jo3rn/blockchAIn pull request #14
Opened 2021-04-07 11:38 UTC by ActionHOSchT

Anzeige des Datums ändern #10

Edited Code to answer the question.

2021-04-08 14:28 UTC, jo3rn requested changes

2021-04-08 14:28 UTC, jo3rn commented on de/jo3rn/horstlchain/Block.java
> +import org.w3c.dom.CDATASection;
Hier ist ein nicht zugehöriges import statement reingerutscht

2021-04-08 14:28 UTC, jo3rn commented on de/jo3rn/horstlchain/Block.java
> +        .format(DateTimeFormatter.ofPattern("uuuu.MM.dd-HH:mm:ss'(der 'D'. Tag des Jahres)'"));
fast richtig, fehlt nur noch das Leerzeichen vor der `(` Klammer, damit es exakt die gewünschte Ausgabe von #10 erzeugt.

2021-04-08 14:44 UTC, ActionHOSchT commented on de/jo3rn/horstlchain/Block.java
> +import org.w3c.dom.CDATASection;
Danke für den Hinweis. 
Das Format hatte ich von w3c bezogen.

2021-04-08 15:18 UTC, jo3rn commented
Perfekt

2021-04-09 12:38 UTC, jo3rn approved these changes

2021-04-09 12:38 UTC, merged